version: '3.7'

services:
  server:
    container_name: tqbackend
    restart: unless-stopped
    build: ./server
    ports:
      - '2017:2017'
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
    networks:
      - internal
    depends_on:
      - db
  client:
    container_name: tqfrontend
    restart: unless-stopped
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
    networks:
      - internal
    stdin_open: true
  db:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - mongo_config:/config/configdb
    networks:
      - internal

networks:
  internal:

volumes:
  mongo_data: {}
  mongo_config: {}
